services:
  postgres:
    image: postgres:14
    container_name: postgres-sodep
    environment:
      POSTGRES_DB: prueba_tecnica
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sodep-network

volumes:
  postgres_data:

networks:
  sodep-network:
    driver: bridge
